#Pastas usadas no Conversor de Vídeo
#Tue Nov 04 23:11:43 BRT 2025
pastaDestino=F\:\\Khaos\\Meus V\u00EDdeos\\Variados
pastaOrigem=F\:\\Khaos\\Meus V\u00EDdeos\\S\u00E9ries\\Pinguim\\1 Temporada\\Pinguim S01E01 WEB-DL 1080p x264 DUAL 5.1
